// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_recover from "./routes/auth/recover.tsx";
import * as $auth_signup from "./routes/auth/signup.tsx";
import * as $auth_update_password from "./routes/auth/update-password.tsx";
import * as $index from "./routes/index.tsx";
import * as $protected from "./routes/protected.tsx";
import * as $AuthForm from "./islands/AuthForm.tsx";
import * as $RecoverForm from "./islands/RecoverForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/recover.tsx": $auth_recover,
    "./routes/auth/signup.tsx": $auth_signup,
    "./routes/auth/update-password.tsx": $auth_update_password,
    "./routes/index.tsx": $index,
    "./routes/protected.tsx": $protected,
  },
  islands: {
    "./islands/AuthForm.tsx": $AuthForm,
    "./islands/RecoverForm.tsx": $RecoverForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
